### ISSUE TITLE
Update for VisualVM 2.0

### ISSUE THREAD

**Issue by jisedlac** [irockel/tda#20]
VisualVM 2.0 has been released and does not support plugins for VisualVM 1.x.

You may want to update the TDA plugin for VisualVM 2.0. Changing imports from `com.sun.tools.visualvm.*` to `org.graalvm.visualvm.*` and updating dependency versions should be enough.

I'm ready to provide any assistance if needed.

**Comment by irockel** [comment]
Updated tda integration to Visual VM 2.0, changed minimum jdk used inside TDA to 1.8. Will provide new nbms to you when maintenance release 2.4 is ready.

**Comment by irockel** [comment]
Issue for VisualVM Release: https://github.com/oracle/visualvm/issues/224

**Comment by jisedlac** [comment]
We've tested the VisualVM modules and found two minor issues. Could you please address them before releasing on the VisualVM Plugin Center?

1. Currently two modules would be visible on the Plugin Center: VisualVM-TDA-Module and VisualVM-Logfile-Module. Would be better if only the first module was visible to the user - it represents the whole plugin from the user's perspective
![tda_modules](https://user-images.githubusercontent.com/22048050/92578713-83df1580-f28c-11ea-8a23-1697eb524cc4.png)

2. The TDA Options category should display at the end, after the standard VisualVM categories. Consider using TDA instead of the full name to keep the item small, but this is up to you - not a requirement.
![tda_options](https://user-images.githubusercontent.com/22048050/92578905-cf91bf00-f28c-11ea-95aa-475c62738574.png)

**Comment by irockel** [comment]
Adjusted plugin configuration as requested. The plugin files in the 2.4 release are updated with the changes.

**Comment by jisedlac** [comment]
Verified, thanks!
